apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mongo
  namespace: stateful-app
spec: 
  serviceName: mongo-svc
  replicas: 1
  selector:
    matchLabels: 
      app: mongo
  template: 
    metadata: 
      labels:
        app: mong
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          VolumeMounts:
            - name: mongo-data
              mountPath: /data/db
volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec: 
      accessMode:
        - ReadWriteOnce
      resources: 
        requests: 
          storage: 1Gi
