apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: mongo-storage
provisioner: kubernetes.io/no-provider
volumeBindingMode: WaitForFirstConsumer  # pvc waits until a pod uses it before binding  other optoion is Immediate pvc binds as soon as it is created 
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: gp2
mountOptions: 
  - noatime
  - nodiratime
